### ISSUE TITLE
Question about quantization method?

### ISSUE THREAD

**Issue by bangawayoo** [cornell-zhang/dnn-quant-ocs#2]
Hi, thank you for sharing the code.
I was wondering whether the quantization method used waas "per-channel" or "per-layer".
I am having trouble looking up the setup in your paper.

Thank you in advance.

Best regards.

**Comment by rzhao01** [comment]
Hi there,

We used a per-layer quantization method. There is a single scaling factor for each layer.

**Comment by bangawayoo** [comment]
Thank you for the reply :)
